name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    strategy:
      matrix:
        include:
          - endpoint_uuid: '72a033c0-c9b4-4815-980b-b7cde5d957bf'
            user_endpoint_config: '{ "WORKING_DIR": "/home/kamping"}'
            clone_endpoint_config: '{ "WORKING_DIR": "/home/kamping"}'
            
    runs-on: ubuntu-latest
    environment: hpcci

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: run Artifact1
        id: a1
        uses: ValHayot/globus-compute-github-action@v1
        with:
          client_id: ${{ secrets.GLOBUS_COMPUTE_CLIENT_ID }}
          client_secret: ${{ secrets.GLOBUS_COMPUTE_CLIENT_SECRET }}
          endpoint_uuid: ${{ matrix.endpoint_uuid }}
          shell_cmd: "cd gc-action-temp/kamping-reproducibility/artifact1 && bash 00_fetch_source.sh && bash 01_build.sh && bash 02_run_tests.sh"
          user_endpoint_config: ${{ matrix.user_endpoint_config }}
          clone_endpoint_config: ${{ matrix.clone_endpoint_config }}
      - name: Archive a1 output stdout
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: a1-stdout-${{ matrix.endpoint_uuid }}
          path: ${{ steps.a1.outputs.stdout }}
      - name: Archive a1 output stderr
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: a1-stderr-${{ matrix.endpoint_uuid }}
          path: ${{ steps.a1.outputs.stderr }}
      - name: run Artifact2
        id: a2
        uses: ValHayot/globus-compute-github-action@v1
        with:
          client_id: ${{ secrets.GLOBUS_COMPUTE_CLIENT_ID }}
          client_secret: ${{ secrets.GLOBUS_COMPUTE_CLIENT_SECRET }}
          endpoint_uuid: ${{ matrix.endpoint_uuid }}
          shell_cmd: "cd gc-action-temp/kamping-reproducibility/artifact2 && bash 00_fetch_source.sh && bash 01_build_benchmarks.sh && bash 02_count_loc.sh && bash 03_run_sorting.sh && bash 04_run_bfs.sh && 05_eval_sorting.sh && 06_eval_bfs.sh || true"
          user_endpoint_config: ${{ matrix.user_endpoint_config }}
          clone_endpoint_config: ${{ matrix.clone_endpoint_config }}
      - name: Archive a1 output stdout
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: a2-stdout-${{ matrix.endpoint_uuid }}
          path: ${{ steps.a2.outputs.stdout }}
      - name: Archive a2 output stderr
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: a2-stderr-${{ matrix.endpoint_uuid }}
          path: ${{ steps.a2.outputs.stderr }}
